### ISSUE TITLE
Drone starts drifting

### ISSUE THREAD

**Issue by vsafin-copart** [hybridgroup/node-bebop#22]
It seems like once I make drone take off using drone.take Off() and then start doing any other movements clockwise or right and left it start s drifting a lot all over the place. I am wondering if I am missing something

Program is really straight forward with takeoff and clockwise wrapped into setTimeout just like in the dance.js example I would expect drone to stay in place but it drifts away for at few meters in the matter of 10-15 sec

**Comment by deadprogram** [comment]
Hi @vsafin-copart you should check the firmware version on the drone. Also, you might want to use https://github.com/hybridgroup/node-bebop#speedsettingshullprotectionpresent or https://github.com/hybridgroup/node-bebop#speedsettingsoutdooroutdoor depending on your environment.

**Comment by xliefde** [comment]
im having the same problem, the firmware version on the drone is up to date (2.0.57)

**Comment by deadprogram** [comment]
Quite a few people seem to have had problems with drift on the Bebop, their forums have a lot of threads like https://community.parrot.com/t5/Bebop-Drone/Bebop-started-drifting-again/m-p/131673/highlight/true#M13193

I suggest running the calibration (via the iOS or Android app), and see if that helps out. I do not personally recommend doing firmware downgrades, as a couple people recommended on that thread, simply because it introduced different problems without really solving any for me (at least at that point).

**Comment by xliefde** [comment]
The strange thing is that when i use the free flight app on my phone ,it's not drifting ,it only starts drifting when i'm using the API

**Comment by deadprogram** [comment]
I had a similar problem a couple times, and I cannot recall offhand what I did about it. Thinking...

**Comment by deadprogram** [comment]
Hi, everyone

I pushed a new branch https://github.com/hybridgroup/node-bebop/tree/bugfix/control-pcmd that handles the PCMD flag differently. Still testing it today, but please feel free to give it a try and let how it works for you.

**Comment by deadprogram** [comment]
Hi everyone we've just released v0.5.0 which has many improvements including greatly improved stability when hovering. Please give it a try, and if needed reopen this issue. Thanks!
