### ISSUE TITLE
 Compatibility  with bebop 1 ?

### ISSUE THREAD

**Issue by py4object** [hybridgroup/node-bebop#29]
Hey i'm wondering what should i do to make this api compatible with be
currently it's working but the drone is hella drifting and hard to control

**Comment by deadprogram** [comment]
Hi, @py4object I pushed a branch named https://github.com/hybridgroup/node-bebop/tree/bugfix/control-pcmd that seems to fly with greater stability for me with the 2.0.57+ firmware.

Please give it a try and see how it works for you.

I also added a new alias command `drone.level();` for the poorly named `drone.stop()` to reset the PCMD flag to 0, which is what I think the root cause for the stability problem with the latest firmware.

**Comment by deadprogram** [comment]
Hi @py4object we've just released v0.5.0 which has many improvements including the stability one I previously mentioned. Please give it a try, and if needed reopen this issue. Thanks!

**Comment by py4object** [comment]
Hi sorry ,I didn't have the time to try it out 
Now that i just did ,it's flying really stable ! cheers

**Comment by deadprogram** [comment]
Glad to hear it! :helicopter:

**Comment by CE93Geek** [comment]
@py4object hi, what firmware did you have on bebop1 when it was stable?
